### ISSUE TITLE
upload msql file ... and how to install it

### ISSUE THREAD

**Issue by alidz1982** [abhiyadav1323/WeShare#1]

**Comment by abhiyadav1323** [comment]
I have given the schema for all the 3 tables that are required in the Readme page. Have a look at that. U can create tables in MySQL with those schemas.
Hope it helps.🙂

**Comment by abhiyadav1323** [comment]
I have given the schema for all the 3 tables that are required in the Readme page. Have a look at that. U can create tables in MySQL with those schemas.
Hope it helps.🙂
